version: '3.2'

services:
  db:
    image: 'postgres:10-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  app:
    depends_on:
      - 'db'
      - chrome
    build: .
    command: foreman start -f Procfile.dev -p 3000
    ports:
      - "3000:3000"
      - "35729:35729"
      - "${CAPYBARA_SERVER_PORT:-3434}:${CAPYBARA_SERVER_PORT:-3434}"
    environment:
      - DATABASE_HOST=db
      - BUNDLE_PATH=/bundle/vendor
      - HUB_URL=http://chrome:4444/wd/hub
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
      - bundle_path:/bundle

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  chrome:
    image: selenium/standalone-chrome:3.141.59-zirconium # this version should match that of the selenium-webdriver gem (see Gemfile)
    volumes:
      - /dev/shm:/dev/shm

volumes:
  redis:
  postgres:
  bundle_path: