version: '3.2'

services:
  db:
    image: 'postgres:10-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  app:
    depends_on:
      - 'db'
      - 'webdriver_chrome'
    build: .
    command: foreman start -f Procfile.dev -p 3000
    ports:
      - "3000:3000"
      - "35729:35729"
      - "${CAPYBARA_SERVER_PORT:-3434}:${CAPYBARA_SERVER_PORT:-3434}"
    environment:
      - DATABASE_HOST=db
      - BUNDLE_PATH=/bundle/vendor
      # Convey which port Capybara should be starting test servers on; fail loudly
      # if we've neglected to configure it.
      - CAPYBARA_SERVER_PORT="${CAPYBARA_SERVER_PORT:-3434}"
      # The test server WILL NOT BE AVAILABLE from outside the container if it binds 
      # to 127.0.0.1. It must bind to 0.0.0.0 to be exposed to the outside world.
      - CAPYBARA_SERVER_HOST="${CAPYBARA_SERVER_HOST:-0.0.0.0}"
    
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
      - bundle_path:/bundle

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  webdriver_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900

volumes:
  redis:
  postgres:
  bundle_path: